<?php

/**
 * @file
 * Code for the User Create By Role module.
 */



function user_generate_init(){
    
     global $user;
     if(arg(0)!= 'user' && ($user->uid > 1) && (!$user->mail) ){
         drupal_goto('user/'.$user->uid.'/edit');
     }
     
}

/**
 * Implements hook_menu().
 */
function user_generate_menu() {
  $items['generate_login_key'] = array(
    'title' => t('Generate Login Key'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('generate_login_key_form'),
    'access arguments' => array('administer Key Generator'),
    'type' => MENU_NORMAL_ITEM,  
  );
  $items['generate_single_key'] = array(
    'title' => t('Generate Single Key'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('generate_single_key_form'),
    'access arguments' => array('administer Key Generator'),
    'type' => MENU_NORMAL_ITEM,  
  ); 
  
  $items['login'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('login_by_accesskey_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,  
  );
  return $items;
}




function user_generate_form_alter(&$form, &$form_state, $form_id) {    
    if($form_id == 'add_medical_condition_node_form'){
      if(isset($form_state['node']->nid) && $form_state['node']->nid) {
            $form['actions']['submit']['#submit'][] ='node_edit_custom_submit';
        }else {
            $form['actions']['submit']['#submit'][] ='node_add_custom_submit'; 
        }
      
    }
    if($form_id == 'pfff_login'){
        $form['mail'] = array(
            '#type' => 'textfield',
            '#title' => t('Email'),
            '#required' => TRUE,
            '#size' => 30,
        );
        $form['#validate'][] = 'custom_pfff_validation';
    }
}

function custom_pfff_validation($form, &$form_state) {
        $custom_mail = $form_state['values']['mail'];
        if($custom_mail && !valid_email_address($form_state['values']['mail'])){
         form_set_error('pfff_validate', t('Enter valid email id'));   
        }
        
}
function node_add_custom_submit($form, &$form_state) {
        unset($_GET['destination']);
        unset($_REQUEST['edit']['destination']); 
        $form_state['redirect'] = 'node/add/add-medical-condition';
}

function node_edit_custom_submit($form, &$form_state) {
        unset($_GET['destination']);
        unset($_REQUEST['edit']['destination']); 
        $form_state['redirect'] = 'list-medical-conditions';
}


function login_by_accesskey_form(){
    
    $form['username'] = array(
    '#type' => 'password',
    '#title' => t('Enter Access Key'),
    '#required' => TRUE,
    '#size' => 30,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Login'),
  );
  return $form;
    
}

function login_by_accesskey_form_submit($form_id, &$form_state){
    global $user;
   // $username = $form_state['values']['username'];
    $user->uid = 1; //= user_load(1);
    
//    print '<pre>';
//    print_r($user); exit;
}


function generate_login_key_form(){

   $form['num'] = array(
    '#type' => 'textfield',
    '#title' => t('How many users access would you like to generate?'),
    '#default_value' => 10,
    '#size' => 10,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate'),
  );
  return $form;
}


function generate_single_key_form(){
    
        $form['accesskey'] = array(
            '#type' => 'textfield',
            '#title' => t('Enter desirable key name would you like to generate?'),
            '#size' => 50,
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Generate'),
        );
        
        $form['#validate'][0] = 'accesskey_validation';
        return $form;
        
}
   
function accesskey_validation( &$form, &$form_state ){
   $accesskey = trim($form_state['values']['accesskey']);
   
   $output['msg'] = '';
   if(!$accesskey){
     $output['msg'] = t('Enter value of access key name.');   
   } else {
       
        $ret = _user_generate_check_is_accesskey_exists($accesskey);
        if($ret){
      $output['msg'] = t('Acess key already used.');     
        }
   }

   
   
   if($output['msg']){
       form_set_error('accesskey', $output['msg']);
   }  
}
function generate_single_key_submit($form_id, &$form_state){
  $username = $form_state['values']['accesskey'];
  portableclinic_users_create($values['num'], $time_range, $roles, $username );
  
}   

/**
 * hook_submit();
 * @param type $form_id
 * @param type $form_state 
 */
function generate_login_key_form_submit($form_id, &$form_state) {
 // module_load_include('inc', 'devel_generate');
  $values = $form_state['values'];
  $time_range = 1;
  $roles = array('0' => 0,'4' => 4);   
  portableclinic_users_create($values['num'], $time_range, $roles );
}

/**
 * Generate some users.
 *
 * @param $num
 *  Number of users to generate.
 * @param $kill
 *  Boolean that indicates if existing users should be removed first.
 * @param $age
 *  The max age of each randomly-generated user, in seconds.
 * @param $roles
 *  An array of role IDs that the users should receive.
 */

function portableclinic_users_create($num, $age = 0, $roles = array(), $username = '') {
 
  if ($num > 0) {
    $names = array();
    while (count($names) < $num) {
        if(!$username){
      $name = generateStrongLoginAccesskey(10, FALSE, 'lud');
        } else {
      $name =  $username;
        }
      $names[$name] = '';
    }

    if (empty($roles)) {
      $roles = array(DRUPAL_AUTHENTICATED_RID);
    }
    foreach ($names as $name => $value) {
      $edit = array(
        'uid'     => NULL, 
        'name'    => $name,
        'pass'    => 'demo',
        'mail'    => '',
        'status'  => 1,
        'created' => REQUEST_TIME,
        'roles' => drupal_map_assoc($roles),
        'language' => LANGUAGE_NONE,
      );
      $account = user_save(drupal_anonymous_user(), $edit);
    }
  }
  drupal_set_message(t('!num_users created.', array('!num_users' => format_plural($num, '1 User Login Key', '@count User Login Keys'))));
}


function _user_generate_check_is_accesskey_exists($accesskey) {
  return db_query("SELECT COUNT(u.name) count FROM {users} u WHERE LOWER(u.name) = LOWER(:username)", array(':username' => $accesskey))->fetchField();
}

function generateStrongLoginAccesskey($length = 9, $add_dashes = false, $available_sets = 'luds')
{
	$sets = array();
	if(strpos($available_sets, 'l') !== false)
		$sets[] = 'abcdefghjkmnpqrstuvwxyz';
	if(strpos($available_sets, 'u') !== false)
		$sets[] = 'ABCDEFGHJKMNPQRSTUVWXYZ';
	if(strpos($available_sets, 'd') !== false)
		$sets[] = '23456789';
	if(strpos($available_sets, 's') !== false)
		$sets[] = '!@#$%&*?';
 
	$all = '';
	$password = '';
	foreach($sets as $set)
	{
		$password .= $set[array_rand(str_split($set))];
		$all .= $set;
	}
 
	$all = str_split($all);
	for($i = 0; $i < $length - count($sets); $i++)
		$password .= $all[array_rand($all)];
 
	$password = str_shuffle($password);
 
	if(!$add_dashes)
		return $password;
 
	$dash_len = floor(sqrt($length));
	$dash_str = '';
	while(strlen($password) > $dash_len)
	{
		$dash_str .= substr($password, 0, $dash_len) . '-';
		$password = substr($password, $dash_len);
	}
	$dash_str .= $password;
	return $dash_str;
}


